spring:
  application:
    name: restaurant-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: client
          uri: lb://client
          predicates:
            - Path=/client/**
        - id: client2
          uri: lb://client2
          predicates:
            - Path=/client2/**
server:
  port: 8083
eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:8761/eureka
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway